repos:
  - repo: local
    hooks:
      - id: black
        name: "[Black] Code Formatter"
        entry: black --config=pyproject.toml
        language: system
        types: [file, python]
        stages: [commit]

  - repo: local
    hooks:
      - id: isort
        name: "[isort] Import Sorting"
        entry: isort --sp=pyproject.toml
        language: system
        types: [file, python]
        stages: [commit]

  - repo: local
    hooks:
      - id: flake8
        name: "[flake8] Linter"
        entry: flake8 --toml-config=pyproject.toml
        language: system
        types: [file, python]
        stages: [commit]

  - repo: local
    hooks:
      - id: mypy
        name: "[Mypy] Type Checker"
        entry: mypy --config-file=pyproject.toml
        language: system
        types: [file, python]
        stages: [commit]
